[package]
authors = ["Sean Bowe <sean@z.cash>", , "Alex Vlasov <alex.m.vlasov@gmail.com>"]
description = "Cryptographic library for Zcash Sapling with more content"
documentation = "https://github.com/matterinc/sapling"
homepage = "https://github.com/matterinc/sapling"
license = "MIT/Apache-2.0"
name = "sapling-crypto"
repository = "https://github.com/matterinc/sapling"
version = "0.0.2"
 
[dependencies]
rand = "0.4"
digest = "0.7"
byteorder = "1"
ff = { version = "0.4", features = ["derive"] }
pairing = { git = 'https://github.com/matterinc/pairing', features = ["expose-arith"] }
Bellman = { git = 'https://github.com/matterinc/ballman'}

[dependencies.blake2-rfc]
git = "https://github.com/gtank/blake2-rfc"
rev = "7a5b5fc99ae483a0043db7547fb79a6fa44b88a9"

[dev-dependencies]
hex-literal = "0.1"
rust-crypto = "0.2"
